# Generated by Django 5.1 on 2024-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
