# Generated by Django 5.1 on 2024-10-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_entregatarea_revisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='archivos/tareas/'),
        ),
    ]
