# Generated by Django 5.1 on 2024-10-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='cliente.materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='cliente.materia'),
            preserve_default=False,
        ),
    ]
