# Generated by Django 5.1 on 2024-10-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cuestionario_materia_examen_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('OM', 'Opción Múltiple'), ('FV', 'Falso o Verdadero'), ('RL', 'Rellenar')], default='OM', max_length=2),
        ),
    ]
