# Generated by Django 5.1 on 2024-10-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='cliente.cuestionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cliente.cuestionario'),
            preserve_default=False,
        ),
    ]
