# Generated by Django 5.1 on 2024-10-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_examen_cuestionario_pregunta_cuestionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='materia',
        ),
    ]
