# Generated by Django 5.1 on 2024-10-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_pregunta_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
