# Generated by Django 5.1 on 2024-10-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_examenentregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_examen', to='cliente.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_entregados', to='cliente.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamenEntregado',
        ),
    ]
