# Generated by Django 5.1 on 2024-10-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_examenalumno_delete_examenentregado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamenAlumno',
            new_name='ExamenRevision',
        ),
    ]
