# Generated by Django 5.1 on 2024-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_rename_examenalumno_examenrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrevision',
            name='respuestas_usuario',
            field=models.JSONField(default=list),
        ),
    ]
