# Generated by Django 5.1.7 on 2025-03-25 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_alter_cuestionario_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLogeado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='cliente.usuario')),
            ],
        ),
    ]
